### ISSUE TITLE
Unable to create a new service

### ISSUE THREAD

**Issue by leovarmak** [clay-run/clay-cli#8]
I am unable to create a new service. I get an error say `error: unknown option -t`

**Comment by kareemamin** [comment]
Thanks @leovarmak for trying Clay out and sorry you hit that error, thanks for letting us know. We've deprecated the template function and support for creating alexa clay functions from the command line. Since we're not open to the public yet and making changes quickly, we haven't updated that yet in our documentation but would love for you to try it out in our new workflow, we'll send you an email with instructions.

**Comment by son1112** [comment]
@kareemamin I am attempting to use this option as well while following [this tutorial](https://medium.com/clay-labs/code-your-first-alexa-skill-in-30-ish-seconds-using-clay-ready-go-8293ee1761ac). I would love to try out the new workflow as you mentioned.
